export const GET_ALL_CATEGORY = "[PRODUCT APP] GET ALL CATEGORY";
export const GET_ALL_PRODUCT = "[PRODUCT APP] GET ALL PRODUCT";
export const ADD_NEW_PRODUCT = "[PRODUCT APP] ADD ALL PRODUCT";
export const UPDATE_NEW_PRODUCT = "[PRODUCT APP] UPDATE PRODUCT";
export const DELETE_NEW_PRODUCT = "[PRODUCT APP] DELETE PRODUCT";
